spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: demoservice
  thymeleaf:
    cache: false
server:
  port: 9091
  #ssl:
    #key-store: C:\Users\GDCV\Documents\Spring\workspace\create-p12\cert.p12
    #key-store-password: Duy12345.
    #keyStoreType: PKCS12